version: "3.8"

services:
  echo-api-prod:
    container_name: echo-api-prod
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/Dockerfile.api
      target: production
    command: npm run start:debug
    restart: always
    env_file:
      - ../envs/.production.env
    volumes:
      - ../api:/usr/src/api
      - /usr/src/api/node_modules
    networks:
      - echo-network
    ports:
      - 3000:3000
    depends_on:
      echo-postgres:
        condition: service_healthy
      echo-mongodb:
        condition: service_healthy
      echo-rabbitmq:
        condition: service_healthy

  echo-mongodb:
    image: mongo
    container_name: echo-mongodb
    env_file:
      - ../envs/.production.env
    networks:
      - echo-network
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  echo-postgres:
    container_name: echo-postgres
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/postgres/Dockerfile.postgres
    restart: always
    env_file:
      - ../envs/.production.env
    volumes:
      - echo_dev_db_data:/var/lib/postgresql/data
    networks:
      - echo-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  echo-rabbitmq:
    container_name: echo-rabbitmq
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/rabbitmq/Dockerfile.rabbitmq
    networks:
      - echo-network
    ports:
      - 5671:5671
      - 1883:1883
      - 15671:15671
      - 15672:15672
      - 15675:15675
    volumes:
      - echo_dev_rabbitmq_data:/var/lib/rabbitmq/
      - echo_dev_rabbitmq_log:/var/log/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  echo-network:
    name: echo-network
    driver: bridge

volumes:
  echo_dev_db_data:
    name: echo_dev_db_data
  echo_dev_rabbitmq_data:
    name: echo_dev_rabbitmq_data
  echo_dev_rabbitmq_log:
    name: echo_dev_rabbitmq_log
