version: "3.8"

services:
  setup:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/setup/Dockerfile
      args:
        - SSL_CERTS_PATH=/usr/share/certs
    user: '0'
    volumes:
      - ssl_certs:/usr/share/certs

volumes:
  ssl_certs:
    name: ssl_certs