FROM rabbitmq:3.11.13-management-alpine

COPY ./docker/dockerfiles/rabbitmq/rabbitmq.conf /etc/rabbitmq
COPY ./docker/dockerfiles/rabbitmq/definitions.json /etc/rabbitmq

RUN cat /etc/rabbitmq/rabbitmq.conf
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_stomp rabbitmq_stomp rabbitmq_web_mqtt rabbitmq_amqp1_0
CMD ["rabbitmq-server"]
